[project]
name = "mvlab"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ramiro Willmersdorf", email = "ramiro.willmersdorf@ufpe.br" }
]
requires-python = ">=3.11"
dependencies = [
    "marimo>=0.23.9",
    "matplotlib>=3.10.9",
    "numpy>=2.4.6",
    "ruff>=0.15.17",
    "scipy>=1.17.1",
    "sympy>=1.14.0",
]

[build-system]
requires = ["uv_build>=0.9.18,<0.10.0"]
build-backend = "uv_build"
